// <auto-generated />
using ITWEB6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ITWEB6.Migrations
{
    [DbContext(typeof(FitnessBoysContext))]
    partial class FitnessBoysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITWEB6.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("ProgramId");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("ITWEB6.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsRepetition");

                    b.Property<string>("Name");

                    b.Property<int>("Repetitions");

                    b.Property<int>("Sets");

                    b.Property<double>("Time");

                    b.HasKey("Id");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("ITWEB6.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Creater");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Program");
                });

            modelBuilder.Entity("ITWEB6.Models.ProgramExercise", b =>
                {
                    b.Property<int>("ExerciseId");

                    b.Property<int>("ProgramId");

                    b.HasKey("ExerciseId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("ProgramExercise");
                });

            modelBuilder.Entity("ITWEB6.Models.Activity", b =>
                {
                    b.HasOne("ITWEB6.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");
                });

            modelBuilder.Entity("ITWEB6.Models.ProgramExercise", b =>
                {
                    b.HasOne("ITWEB6.Models.Exercise", "Exercise")
                        .WithMany("ProgramExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ITWEB6.Models.Program", "Program")
                        .WithMany("ProgramExercises")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
